# Form implementation generated from reading ui file 'frm_exportar_anuncios_para_compatibilidade.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FrmExportarAnunciosParaCompatibilidade(object):
    def setupUi(self, FrmExportarAnunciosParaCompatibilidade):
        FrmExportarAnunciosParaCompatibilidade.setObjectName("FrmExportarAnunciosParaCompatibilidade")
        FrmExportarAnunciosParaCompatibilidade.resize(623, 423)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(FrmExportarAnunciosParaCompatibilidade)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gbxDadosEntrada = QtWidgets.QGroupBox(parent=FrmExportarAnunciosParaCompatibilidade)
        self.gbxDadosEntrada.setObjectName("gbxDadosEntrada")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gbxDadosEntrada)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.gbxDadosEntrada)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.edtArquivoDestino = QtWidgets.QLineEdit(parent=self.gbxDadosEntrada)
        self.edtArquivoDestino.setReadOnly(True)
        self.edtArquivoDestino.setObjectName("edtArquivoDestino")
        self.horizontalLayout_3.addWidget(self.edtArquivoDestino)
        self.btnInformarDiretorio = QtWidgets.QPushButton(parent=self.gbxDadosEntrada)
        self.btnInformarDiretorio.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icones/icones/open.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnInformarDiretorio.setIcon(icon)
        self.btnInformarDiretorio.setObjectName("btnInformarDiretorio")
        self.horizontalLayout_3.addWidget(self.btnInformarDiretorio)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.gbxDadosEntrada)
        self.gbxPreVisualizacao = QtWidgets.QGroupBox(parent=FrmExportarAnunciosParaCompatibilidade)
        self.gbxPreVisualizacao.setObjectName("gbxPreVisualizacao")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gbxPreVisualizacao)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tblAnuncios = QtWidgets.QTableView(parent=self.gbxPreVisualizacao)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tblAnuncios.setFont(font)
        self.tblAnuncios.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tblAnuncios.setAlternatingRowColors(True)
        self.tblAnuncios.setGridStyle(QtCore.Qt.PenStyle.DashLine)
        self.tblAnuncios.setObjectName("tblAnuncios")
        self.verticalLayout.addWidget(self.tblAnuncios)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnExportarAnuncios = QtWidgets.QPushButton(parent=self.gbxPreVisualizacao)
        self.btnExportarAnuncios.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icones/icones/excel.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnExportarAnuncios.setIcon(icon1)
        self.btnExportarAnuncios.setObjectName("btnExportarAnuncios")
        self.horizontalLayout_2.addWidget(self.btnExportarAnuncios)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.gbxPreVisualizacao)

        self.retranslateUi(FrmExportarAnunciosParaCompatibilidade)
        QtCore.QMetaObject.connectSlotsByName(FrmExportarAnunciosParaCompatibilidade)

    def retranslateUi(self, FrmExportarAnunciosParaCompatibilidade):
        _translate = QtCore.QCoreApplication.translate
        FrmExportarAnunciosParaCompatibilidade.setWindowTitle(_translate("FrmExportarAnunciosParaCompatibilidade", "Exportar anúncios para compatibilidade"))
        self.gbxDadosEntrada.setTitle(_translate("FrmExportarAnunciosParaCompatibilidade", "Dados de entrada"))
        self.label.setText(_translate("FrmExportarAnunciosParaCompatibilidade", "Diretório de destino:"))
        self.gbxPreVisualizacao.setTitle(_translate("FrmExportarAnunciosParaCompatibilidade", "Pré-visualização"))
        self.btnExportarAnuncios.setText(_translate("FrmExportarAnunciosParaCompatibilidade", "Exportar"))
