# Form implementation generated from reading ui file 'frm_inserir_compatibilidades_meli.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FrmInserirCompatibilidadesMeli(object):
    def setupUi(self, FrmInserirCompatibilidadesMeli):
        FrmInserirCompatibilidadesMeli.setObjectName("FrmInserirCompatibilidadesMeli")
        FrmInserirCompatibilidadesMeli.resize(953, 553)
        FrmInserirCompatibilidadesMeli.setStyleSheet("QPushButton:hover:!pressed {\n"
"    border: 1px solid rgb(3, 33, 92);\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QWidget{\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(FrmInserirCompatibilidadesMeli)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=FrmInserirCompatibilidadesMeli)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.edtPlanilhaMarcaModelosAnos = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.edtPlanilhaMarcaModelosAnos.setReadOnly(True)
        self.edtPlanilhaMarcaModelosAnos.setObjectName("edtPlanilhaMarcaModelosAnos")
        self.gridLayout.addWidget(self.edtPlanilhaMarcaModelosAnos, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.edtPlanilhaCompatibilidade = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.edtPlanilhaCompatibilidade.setReadOnly(True)
        self.edtPlanilhaCompatibilidade.setObjectName("edtPlanilhaCompatibilidade")
        self.gridLayout.addWidget(self.edtPlanilhaCompatibilidade, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.btnAbrirPlanilhaCompatibilidade = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.btnAbrirPlanilhaCompatibilidade.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icones/icones/open.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnAbrirPlanilhaCompatibilidade.setIcon(icon)
        self.btnAbrirPlanilhaCompatibilidade.setObjectName("btnAbrirPlanilhaCompatibilidade")
        self.gridLayout.addWidget(self.btnAbrirPlanilhaCompatibilidade, 0, 2, 1, 1)
        self.btnPlanilhaMarcaModelosAnos = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.btnPlanilhaMarcaModelosAnos.setText("")
        self.btnPlanilhaMarcaModelosAnos.setIcon(icon)
        self.btnPlanilhaMarcaModelosAnos.setObjectName("btnPlanilhaMarcaModelosAnos")
        self.gridLayout.addWidget(self.btnPlanilhaMarcaModelosAnos, 1, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=FrmInserirCompatibilidadesMeli)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tblCompatibilidades = QtWidgets.QTableView(parent=self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tblCompatibilidades.setFont(font)
        self.tblCompatibilidades.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tblCompatibilidades.setAlternatingRowColors(True)
        self.tblCompatibilidades.setGridStyle(QtCore.Qt.PenStyle.DashLine)
        self.tblCompatibilidades.setObjectName("tblCompatibilidades")
        self.verticalLayout.addWidget(self.tblCompatibilidades)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnInserirCompatibilidades = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.btnInserirCompatibilidades.setObjectName("btnInserirCompatibilidades")
        self.horizontalLayout_2.addWidget(self.btnInserirCompatibilidades)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.gbxLogs = QtWidgets.QGroupBox(parent=FrmInserirCompatibilidadesMeli)
        self.gbxLogs.setFlat(False)
        self.gbxLogs.setObjectName("gbxLogs")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.gbxLogs)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.txtLogs = QtWidgets.QPlainTextEdit(parent=self.gbxLogs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtLogs.sizePolicy().hasHeightForWidth())
        self.txtLogs.setSizePolicy(sizePolicy)
        self.txtLogs.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.txtLogs.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.txtLogs.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.txtLogs.setLineWrapMode(QtWidgets.QPlainTextEdit.LineWrapMode.WidgetWidth)
        self.txtLogs.setReadOnly(True)
        self.txtLogs.setTabStopDistance(83.0)
        self.txtLogs.setObjectName("txtLogs")
        self.horizontalLayout_3.addWidget(self.txtLogs)
        self.verticalLayout_2.addWidget(self.gbxLogs)

        self.retranslateUi(FrmInserirCompatibilidadesMeli)
        QtCore.QMetaObject.connectSlotsByName(FrmInserirCompatibilidadesMeli)

    def retranslateUi(self, FrmInserirCompatibilidadesMeli):
        _translate = QtCore.QCoreApplication.translate
        FrmInserirCompatibilidadesMeli.setWindowTitle(_translate("FrmInserirCompatibilidadesMeli", "Compatibilidades"))
        self.groupBox_2.setTitle(_translate("FrmInserirCompatibilidadesMeli", "Dados de entrada"))
        self.label_2.setText(_translate("FrmInserirCompatibilidadesMeli", "Planilha com marcas, modelos e anos"))
        self.label.setText(_translate("FrmInserirCompatibilidadesMeli", "Planilha de compatibildade:"))
        self.groupBox_3.setTitle(_translate("FrmInserirCompatibilidadesMeli", "Pré-visualização"))
        self.btnInserirCompatibilidades.setText(_translate("FrmInserirCompatibilidadesMeli", "Inserir compatiblidades"))
        self.gbxLogs.setTitle(_translate("FrmInserirCompatibilidadesMeli", "Logs"))
