# Form implementation generated from reading ui file 'autenticador.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgAutenticador(object):
    def setupUi(self, dlgAutenticador):
        dlgAutenticador.setObjectName("dlgAutenticador")
        dlgAutenticador.resize(587, 96)
        dlgAutenticador.setSizeGripEnabled(False)
        dlgAutenticador.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(dlgAutenticador)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblAguardandoAutenticacao = QtWidgets.QLabel(parent=dlgAutenticador)
        self.lblAguardandoAutenticacao.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.lblAguardandoAutenticacao.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblAguardandoAutenticacao.setObjectName("lblAguardandoAutenticacao")
        self.verticalLayout.addWidget(self.lblAguardandoAutenticacao)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnAutenticar = QtWidgets.QPushButton(parent=dlgAutenticador)
        self.btnAutenticar.setObjectName("btnAutenticar")
        self.horizontalLayout.addWidget(self.btnAutenticar)
        self.btnCancelar = QtWidgets.QPushButton(parent=dlgAutenticador)
        self.btnCancelar.setObjectName("btnCancelar")
        self.horizontalLayout.addWidget(self.btnCancelar)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(dlgAutenticador)
        QtCore.QMetaObject.connectSlotsByName(dlgAutenticador)

    def retranslateUi(self, dlgAutenticador):
        _translate = QtCore.QCoreApplication.translate
        dlgAutenticador.setWindowTitle(_translate("dlgAutenticador", "Autenticação necessária"))
        self.lblAguardandoAutenticacao.setText(_translate("dlgAutenticador", "<html><head/><body><p><span style=\" font-weight:600;\">Aguardando autenticação no navegador</span></p><p><span style=\" font-weight:600;\">Esta janela fechará automaticamente uma vez que a autenticação tenha sido finalizada com sucesso.</span></p></body></html>"))
        self.btnAutenticar.setText(_translate("dlgAutenticador", "Autenticar"))
        self.btnCancelar.setText(_translate("dlgAutenticador", "Cancelar"))
