# Form implementation generated from reading ui file 'barra_progresso.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BarraDeProgresso(object):
    def setupUi(self, BarraDeProgresso):
        BarraDeProgresso.setObjectName("BarraDeProgresso")
        BarraDeProgresso.resize(306, 64)
        self.verticalLayout = QtWidgets.QVBoxLayout(BarraDeProgresso)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblMensagem = QtWidgets.QLabel(parent=BarraDeProgresso)
        self.lblMensagem.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblMensagem.setObjectName("lblMensagem")
        self.horizontalLayout.addWidget(self.lblMensagem)
        self.progressBar = QtWidgets.QProgressBar(parent=BarraDeProgresso)
        self.progressBar.setStyleSheet("#progressBar {\n"
"    border: 2px solid  rgb(66, 88, 132);\n"
"    border-radius: 5px;\n"
"    background-color: #E0E0E0;\n"
"}\n"
"#progressBar::chunk {\n"
"    background-color: #2196F3;\n"
"    width: 10px; \n"
"    margin: 0.5px;\n"
"}")
        self.progressBar.setMinimum(15)
        self.progressBar.setProperty("value", 25)
        self.progressBar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.progressBar.setTextVisible(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.Direction.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.btnCancelar = QtWidgets.QPushButton(parent=BarraDeProgresso)
        self.btnCancelar.setObjectName("btnCancelar")
        self.horizontalLayout.addWidget(self.btnCancelar)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(BarraDeProgresso)
        self.btnCancelar.clicked.connect(BarraDeProgresso.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(BarraDeProgresso)

    def retranslateUi(self, BarraDeProgresso):
        _translate = QtCore.QCoreApplication.translate
        BarraDeProgresso.setWindowTitle(_translate("BarraDeProgresso", "Progresso"))
        self.lblMensagem.setText(_translate("BarraDeProgresso", "Processando itens"))
        self.btnCancelar.setText(_translate("BarraDeProgresso", "Cancelar"))
