# Form implementation generated from reading ui file 'frm_sobre.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgSobre(object):
    def setupUi(self, dlgSobre):
        dlgSobre.setObjectName("dlgSobre")
        dlgSobre.resize(690, 176)
        dlgSobre.setMinimumSize(QtCore.QSize(690, 120))
        dlgSobre.setMaximumSize(QtCore.QSize(745, 260))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(dlgSobre)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=dlgSobre)
        self.label.setMaximumSize(QtCore.QSize(50, 50))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icones/icones/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=dlgSobre)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frame)
        self.label_2 = QtWidgets.QLabel(parent=dlgSobre)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=dlgSobre)
        self.buttonBox.setMinimumSize(QtCore.QSize(671, 23))
        self.buttonBox.setMaximumSize(QtCore.QSize(671, 23))
        self.buttonBox.setAutoFillBackground(False)
        self.buttonBox.setStyleSheet("")
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(dlgSobre)
        self.buttonBox.rejected.connect(dlgSobre.reject) # type: ignore
        self.buttonBox.accepted.connect(dlgSobre.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgSobre)

    def retranslateUi(self, dlgSobre):
        _translate = QtCore.QCoreApplication.translate
        dlgSobre.setWindowTitle(_translate("dlgSobre", "Wild Horse"))
        self.label_3.setText(_translate("dlgSobre", "ANCESTRIA Integrações"))
        self.label_2.setText(_translate("dlgSobre", "<html><head/><body><p><span style=\" font-weight:600;\">Versão: </span>0.0.1 alfa\\n\\n</p><p>Este software faz integração com o Mercado Livre através de sua API, permitindo, dentre outras atividades, o cadastro de compatibilidades de autopeças</p></body></html>"))
