# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1337, 681)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widgetApenasIcones = QtWidgets.QWidget(parent=self.centralwidget)
        self.widgetApenasIcones.setMinimumSize(QtCore.QSize(71, 0))
        self.widgetApenasIcones.setMaximumSize(QtCore.QSize(71, 16777215))
        self.widgetApenasIcones.setStyleSheet("QWidget{\n"
"    #background-color: rgba(246, 1, 0, 110);\n"
"}\n"
"\n"
"QPushButton {\n"
"    color:white;\n"
"    height: 30px;\n"
"    border:none;\n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"}\n"
"\n"
"QPushButton::checked{\n"
"  background-color: #F5FAFE;\n"
"  color:#1F95EF;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    background-color: #F5FAFE;\n"
"    color:#1F95EF;\n"
"    font-weight:bold;\n"
"}")
        self.widgetApenasIcones.setObjectName("widgetApenasIcones")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widgetApenasIcones)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.widgetApenasIcones)
        self.label.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(4, 14, 143);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icones/icones/logo.jpg"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnShowMenuComTexto = QtWidgets.QPushButton(parent=self.widgetApenasIcones)
        self.btnShowMenuComTexto.setStyleSheet("QPushButton:hover\n"
"{\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    background-color: #F5FAFE;\n"
"    color:#1F95EF;\n"
"    font-weight:bold;\n"
"}\n"
"")
        self.btnShowMenuComTexto.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icones/icones/menu_collapse.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnShowMenuComTexto.setIcon(icon)
        self.btnShowMenuComTexto.setCheckable(False)
        self.btnShowMenuComTexto.setObjectName("btnShowMenuComTexto")
        self.verticalLayout.addWidget(self.btnShowMenuComTexto)
        self.btnMeliSemTexto = QtWidgets.QPushButton(parent=self.widgetApenasIcones)
        self.btnMeliSemTexto.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icones/icones/favicon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnMeliSemTexto.setIcon(icon1)
        self.btnMeliSemTexto.setCheckable(True)
        self.btnMeliSemTexto.setAutoExclusive(True)
        self.btnMeliSemTexto.setObjectName("btnMeliSemTexto")
        self.verticalLayout.addWidget(self.btnMeliSemTexto)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 307, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.btnConfiguracoesSemTexto = QtWidgets.QPushButton(parent=self.widgetApenasIcones)
        self.btnConfiguracoesSemTexto.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icones/icones/configuracoes.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnConfiguracoesSemTexto.setIcon(icon2)
        self.btnConfiguracoesSemTexto.setCheckable(True)
        self.btnConfiguracoesSemTexto.setAutoExclusive(True)
        self.btnConfiguracoesSemTexto.setObjectName("btnConfiguracoesSemTexto")
        self.verticalLayout_3.addWidget(self.btnConfiguracoesSemTexto)
        self.btnSobreSemTexto = QtWidgets.QPushButton(parent=self.widgetApenasIcones)
        self.btnSobreSemTexto.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icones/icones/sobre.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnSobreSemTexto.setIcon(icon3)
        self.btnSobreSemTexto.setCheckable(True)
        self.btnSobreSemTexto.setAutoExclusive(True)
        self.btnSobreSemTexto.setObjectName("btnSobreSemTexto")
        self.verticalLayout_3.addWidget(self.btnSobreSemTexto)
        self.horizontalLayout_3.addWidget(self.widgetApenasIcones)
        self.widgetIconeseNome = QtWidgets.QWidget(parent=self.centralwidget)
        self.widgetIconeseNome.setMinimumSize(QtCore.QSize(191, 0))
        self.widgetIconeseNome.setMaximumSize(QtCore.QSize(191, 16777215))
        self.widgetIconeseNome.setStyleSheet("QWidget{\n"
"    #background-color: rgba(246, 1, 0, 110);\n"
"}\n"
"\n"
"QPushButton {\n"
"    color:white;\n"
"    text-align:left;\n"
"    height: 30px;\n"
"    border:none;\n"
"    padding-left:10px;\n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"}\n"
"\n"
"QPushButton::checked{\n"
"  background-color: #F5FAFE;\n"
"  color:#1F95EF;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    background-color: #F5FAFE;\n"
"    color:#1F95EF;\n"
"    font-weight:bold;\n"
"}")
        self.widgetIconeseNome.setObjectName("widgetIconeseNome")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widgetIconeseNome)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblLogoEmpresa = QtWidgets.QLabel(parent=self.widgetIconeseNome)
        self.lblLogoEmpresa.setMaximumSize(QtCore.QSize(200, 150))
        self.lblLogoEmpresa.setText("")
        self.lblLogoEmpresa.setPixmap(QtGui.QPixmap(":/icones/icones/logo.jpg"))
        self.lblLogoEmpresa.setScaledContents(True)
        self.lblLogoEmpresa.setObjectName("lblLogoEmpresa")
        self.horizontalLayout.addWidget(self.lblLogoEmpresa)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnShowMenuSemTexto = QtWidgets.QPushButton(parent=self.widgetIconeseNome)
        self.btnShowMenuSemTexto.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.btnShowMenuSemTexto.setStyleSheet("QPushButton:hover\n"
"{\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    background-color: #F5FAFE;\n"
"    color:#1F95EF;\n"
"    font-weight:bold;\n"
"}")
        self.btnShowMenuSemTexto.setIcon(icon)
        self.btnShowMenuSemTexto.setCheckable(False)
        self.btnShowMenuSemTexto.setAutoDefault(False)
        self.btnShowMenuSemTexto.setDefault(False)
        self.btnShowMenuSemTexto.setFlat(False)
        self.btnShowMenuSemTexto.setObjectName("btnShowMenuSemTexto")
        self.verticalLayout_2.addWidget(self.btnShowMenuSemTexto)
        self.btnMeliComTexto = QtWidgets.QPushButton(parent=self.widgetIconeseNome)
        self.btnMeliComTexto.setIcon(icon1)
        self.btnMeliComTexto.setIconSize(QtCore.QSize(16, 16))
        self.btnMeliComTexto.setCheckable(True)
        self.btnMeliComTexto.setAutoExclusive(True)
        self.btnMeliComTexto.setObjectName("btnMeliComTexto")
        self.verticalLayout_2.addWidget(self.btnMeliComTexto)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 307, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.btnConfiguracoesComTexto = QtWidgets.QPushButton(parent=self.widgetIconeseNome)
        self.btnConfiguracoesComTexto.setIcon(icon2)
        self.btnConfiguracoesComTexto.setCheckable(True)
        self.btnConfiguracoesComTexto.setAutoExclusive(True)
        self.btnConfiguracoesComTexto.setObjectName("btnConfiguracoesComTexto")
        self.verticalLayout_4.addWidget(self.btnConfiguracoesComTexto)
        self.btnSobreComTexto = QtWidgets.QPushButton(parent=self.widgetIconeseNome)
        self.btnSobreComTexto.setIcon(icon3)
        self.btnSobreComTexto.setCheckable(True)
        self.btnSobreComTexto.setAutoExclusive(True)
        self.btnSobreComTexto.setObjectName("btnSobreComTexto")
        self.verticalLayout_4.addWidget(self.btnSobreComTexto)
        self.horizontalLayout_3.addWidget(self.widgetIconeseNome)
        self.widget_central = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_central.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_central.setObjectName("widget_central")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_central)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frameCentralNomeSistema = QtWidgets.QFrame(parent=self.widget_central)
        self.frameCentralNomeSistema.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frameCentralNomeSistema.setObjectName("frameCentralNomeSistema")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frameCentralNomeSistema)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.lblSigla = QtWidgets.QLabel(parent=self.frameCentralNomeSistema)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.lblSigla.setFont(font)
        self.lblSigla.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblSigla.setWordWrap(True)
        self.lblSigla.setObjectName("lblSigla")
        self.verticalLayout_7.addWidget(self.lblSigla)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.verticalLayout_6.addWidget(self.frameCentralNomeSistema)
        self.horizontalLayout_3.addWidget(self.widget_central)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btnMeliSemTexto.toggled['bool'].connect(self.btnMeliComTexto.setChecked) # type: ignore
        self.btnSobreSemTexto.toggled['bool'].connect(self.btnSobreComTexto.setChecked) # type: ignore
        self.btnMeliComTexto.toggled['bool'].connect(self.btnMeliSemTexto.setChecked) # type: ignore
        self.btnSobreComTexto.toggled['bool'].connect(self.btnSobreSemTexto.setChecked) # type: ignore
        self.btnShowMenuSemTexto.clicked['bool'].connect(self.widgetApenasIcones.setHidden) # type: ignore
        self.btnShowMenuSemTexto.clicked['bool'].connect(self.widgetIconeseNome.setVisible) # type: ignore
        self.btnShowMenuComTexto.clicked['bool'].connect(self.widgetIconeseNome.setHidden) # type: ignore
        self.btnShowMenuComTexto.clicked['bool'].connect(self.widgetApenasIcones.setVisible) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wild Horse Motors"))
        self.btnShowMenuComTexto.setToolTip(_translate("MainWindow", "Expandir menu"))
        self.btnMeliSemTexto.setToolTip(_translate("MainWindow", "Abrir opções de integração com o Mercado Livre"))
        self.btnConfiguracoesSemTexto.setToolTip(_translate("MainWindow", "Configurações"))
        self.btnConfiguracoesSemTexto.setStatusTip(_translate("MainWindow", "Sobre o sistema"))
        self.btnSobreSemTexto.setToolTip(_translate("MainWindow", "Sobre o sistema"))
        self.btnSobreSemTexto.setStatusTip(_translate("MainWindow", "Sobre o sistema"))
        self.btnShowMenuSemTexto.setToolTip(_translate("MainWindow", "Ativiar menu simplificado"))
        self.btnShowMenuSemTexto.setText(_translate("MainWindow", "  Menu simplificado"))
        self.btnMeliComTexto.setToolTip(_translate("MainWindow", "Abrir opções de integração com o Mercado Livre"))
        self.btnMeliComTexto.setText(_translate("MainWindow", "Integração Mercado Livre"))
        self.btnConfiguracoesComTexto.setToolTip(_translate("MainWindow", "Configurações"))
        self.btnConfiguracoesComTexto.setStatusTip(_translate("MainWindow", "Sobre o sistema"))
        self.btnConfiguracoesComTexto.setText(_translate("MainWindow", "Configuracões"))
        self.btnSobreComTexto.setToolTip(_translate("MainWindow", "Sobre o sistema"))
        self.btnSobreComTexto.setStatusTip(_translate("MainWindow", "Sobre o sistema"))
        self.btnSobreComTexto.setText(_translate("MainWindow", "Sobre"))
        self.lblSigla.setText(_translate("MainWindow", "Wild Horse Motors"))
